[package]
name = "snake"
version = "0.1.0"
authors = ["Simon Brahan <simon.brahan@frogeducation.com>"]

[lib]
name = "snake"
path = "src/snake/mod.rs"

[dependencies]
rand = "0.4.2"
piston_window = "0.70.0"
num = "0.1"
